export const APP_SETUP = {
    USER_DETAILS :"USER_DETAILS",
    TAB_NAV_MENU:'TAB_NAV_MENU',
    DRAWER_NAV_MENU:"DRAWER_NAV_MENU"
}

export const ASYNC_KEYS = {
    APP_SETUP :"APP_SETUP",
    LAST_LOGIN_DATE:'LAST_LOGIN_DATE',
    IS_LOGGED_IN: 'IS_LOGGED_IN',
}